import fs from "fs";
import path from "path";
import { execSync } from "child_process";

export function installHooks() {
    const gitDir = path.join(process.cwd(), ".git");
    if (!fs.existsSync(gitDir)) return; // not a git repo

    const hooksDir = path.join(gitDir, "hooks");
    if (!fs.existsSync(hooksDir)) fs.mkdirSync(hooksDir, { recursive: true });

    const preCommitPath = path.join(hooksDir, "pre-commit");
    const prePushPath = path.join(hooksDir, "pre-push");

    const preCommitScript = `#!/bin/sh\n# Auto-generated by secret-guardian-ts\nnode ./node_modules/secret-guardian-ts/dist/index.js pre-commit\n`;
    const prePushScript = `#!/bin/sh\n# Auto-generated by secret-guardian-ts\nnode ./node_modules/secret-guardian-ts/dist/index.js pre-push\n`;

    try {
        fs.writeFileSync(preCommitPath, preCommitScript, { mode: 0o755 });
        fs.writeFileSync(prePushPath, prePushScript, { mode: 0o755 });
        try { execSync(`chmod +x "${preCommitPath}" "${prePushPath}"`); } catch(e) {}
    } catch (e) {
        // best-effort — ignore
    }
}

export default installHooks;